####To begin set the working directory and import some of the first necessary libraries -->

setwd("C:/Users/Resterkes/Desktop/R_Class5/week2")
library(dplyr)
library(ggplot2)

####Import Data Frame -->

data <- read.csv("C:/Users/Resterkes/Desktop/R_Class5/week2/activity.csv")
DF_StepsByDate = data %>%
  group_by(date) %>%
  summarize(Total.Daily.Steps = sum(steps, na.rm=TRUE))
hist (DF_StepsByDate$Total.Daily.Steps, breaks =  15, xlim = c(0, 25000), xlab = "Steps in a day", ylab = "number of days", main = "Histogram of Daily Steps") 


####Calculate the mean and median values for steps taken in a day --> #####The mean value:

mean(DF_StepsByDate$Total.Daily.Steps, na.rm = TRUE)

#####The median value:

median(DF_StepsByDate$Total.Daily.Steps, na.rm = TRUE)

####Create a time series plot of average steps in an interval -->

DF_MaxIntervalSteps = data%>%
  group_by(interval) %>%
  summarize(Max.Steps.Interval = mean(steps, na.rm=TRUE))
ggplot(DF_MaxIntervalSteps, aes(interval, Max.Steps.Interval)) +geom_point()+geom_line()+xlab("Minute of the day staring from 0000")+ylab("Average number of steps taken at given minute value")

####Find which interval saw the most steps taken on average -->

DF_MaxIntervalSteps = data%>%
  group_by(interval) %>%
  summarize(Average.Steps.Per.Interval = mean(steps, na.rm=TRUE))
filter(DF_MaxIntervalSteps, Average.Steps.Per.Interval == max(DF_MaxIntervalSteps$Average.Steps.Per.Interval))

#####You see the interval with highest average steps in the interval column of the table. 

####Code to describe and show strategy for inputing missing data -->

##There are several packages designed to help visualize and input missing data.  Install and load such a library.  I chose cats after exploring some common options. 
library(cats)

## the md.pattern function from mice will help you visualize the missing values
md.pattern(data)

\newline The above tables communicate that 15264 rows have no missing values while 2304 rows are missing values in the steps column. It is clear from the tables that neither the date nor interval columns have any missing values. 
## First is to initialize helpful variables that will be used with the function to impute values that are random yet likely given other variables and their related factors. 
init = mice (data, maxit=0)
meth = init$method
predMtrx = init$predictorMatrix
predMtrx[ ,c("date")]=0  ## I remove date as an imputation predictor given that I am curious about steps in an interval on an average or normal day, not a specific date.
imputedD = mice(data, method = meth, predictorMatrix = predMtrx, m = 5, seed = 500)
imputedComplete = complete(imputedD)

\newline New dataframe complete with imputed values can be fed into similar code as earlier to produce a histogram of average steps taken in a day.

DF_StepsByDay = imputedComplete%>%
   group_by(date) %>%
   summarize(Total.Steps.Per.Day = sum(steps))
hist(DF_StepsByDay$Total.Steps.Per.Day, breaks =  15, xlim = c(0, 25000), xlab = "Steps in a day", ylab = "number of days", main = "Histogram of Daily Steps")

####Create a panel plot comparing average interval steps on weekdays vs weekend days -->

##Import the libraries required for the task of separating data by weekday and to easily organize ggplots into panels
library(timeDate)
library(gridExtra)

dataByDate <- imputedComplete
dataByDate$date <- as.Date(dataByDate$date) 
workWeek<- c('Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday')
dataByDate$wrkDays <- factor((weekdays(dataByDate$date) %in% workWeek), levels = c(FALSE, TRUE))
'%!in%' <- Negate('%in%')
dataByDate$wkndDays <- factor((weekdays(dataByDate$date) %!in% workWeek), levels = c(FALSE, TRUE))
weekendData <- dataByDate[dataByDate$wkndDays == TRUE, ]
weekdayData <- dataByDate[dataByDate$wrkDays ==TRUE, ]

weekdayStepsByInterval = weekdayData%>%
  group_by(interval) %>%
  summarize(Max.Steps.Interval = mean(steps, na.rm=TRUE))
plot1 <- ggplot(weekdayStepsByInterval, aes(interval, Max.Steps.Interval)) +geom_point()+geom_line()+xlab("Minute of the day staring from 0000")+ylab("Average number of steps taken at given minute value")+ ggtitle("Averages of Steps on Weekdays")+ ylim(0,250)

weekendStepsByInterval = weekendData%>%
  group_by(interval) %>%
  summarize(Max.Steps.Interval = mean(steps, na.rm=TRUE))
plot2 <- ggplot(weekendStepsByInterval, aes(interval, Max.Steps.Interval)) +geom_point()+geom_line()+xlab("Minute of the day staring from 0000")+ylab("Average number of steps taken at given minute value")+ ggtitle("Averages of Steps on Weekends")+ylim(0,250)

grid.arrange(plot1, plot2, nrow = 1)

